### ISSUE TITLE
Update members email address

### ISSUE THREAD

**Issue by ga630sf** [brandonseydel/MailChimp.Net#135]
Hi Brandon

Mailchimp updated their API V3 on 3rd Nov to permit updating an existing members email address

-----------------------------------------------------
Add the ability to update an existing list member’s email_address through a PATCH or PUT call to /lists/{list_id}/members/{subscriber_hash}
--------------------------------------------------------
When I test using the subscriber_hash of the old email address as the member.Id parameter and supplying the new email address as the member.EmailAddress parameter in Members.AddOrUpdateAsync it just creates a New Member

regards
Steve

**Comment by nicholastic** [comment]
I agree, not being able to change the email address was absurd, I'm glad they fixed this in the API. How's this coming along? I could try to help if you like.

**Comment by MatiasALopez** [comment]
Hi guys,

I need to use this new feature too and I believe it's pretty straightforward to add it. 

I've cloned the repo and made the following changes to the MemberLogic.AddOrUpdateAsync method:

**Before**
```
var response = await client.PutAsJsonAsync($"{listId}/members/{this.Hash(member.EmailAddress.ToLower())}", member, null).ConfigureAwait(false);
```

**After**
```
string memberId = member.Id ?? this.Hash(member.EmailAddress.ToLower());
var response = await client.PutAsJsonAsync($"{listId}/members/{memberId}", member, null).ConfigureAwait(false);
```

So if the Member's Id property has value then it's used to affect the corresponding resource. Otherwise, it generates the Id value from the EmailAddress like before.

Does this makes sense to you? 
If it does it'll be great if you can add this. Or let me know if you want me to send you a PR.

Thanks!

**Comment by yaronguez** [comment]
Any word from @brandonseydel on if this is the right way to go?

**Comment by MatiasALopez** [comment]
Hi @yaronguez .
No, not yet.

**Comment by brandonseydel** [comment]
@MatiasALopez submit a PR please

**Comment by MatiasALopez** [comment]
@brandonseydel Sure, thanks
