### ISSUE TITLE
Getting member by Id

### ISSUE THREAD

**Issue by MichalJankowskii** [brandonseydel/MailChimp.Net#206]
Please let me know if is it possible to acquire information about member by id (MD5) instead of email address?

**Comment by stuartp22** [comment]
This would be really useful...

It looks like the current wrapper converts the email to an MD5 in order to retrieve the list member.  But if we already have the MD5 saved it would be useful to be able to query by this as well, in order to convert a list member to a customer when buying.

Only things I can think of for now are either to create the customer at the same time as the list member, whilst the email address is known, or else save the email address somewhere (e.g. a db associated with the MD5) so a customer can be created when they are buying.

Would welcome any further thoughts...

**Comment by MichalJankowskii** [comment]
I think there should be possibility to use both e-mail and MD5. 

Using e-mail and automatic transformation to MD5 is great. But in my most business cases I have access to MD5 token and I am accessing or updating data by using MD5 token. Please not that MailChimp also recommends to use MD5 for getting information.

For security reasons my customer sends me only MD5 hashes of people from its' lists. This guarantee that e-mails will be not exposed in system. And with that approach I am not able to use this lib because I am not able to modify MD5 value.

Please not that when you will be able to use MD5 you will not need to know customer email address. You will be able to retrieve it from MailChimp db.

**Comment by brandonseydel** [comment]
I can add this functionality extremely easy.  I will allow a hash to be passed instead of a members email address.

**Comment by MichalJankowskii** [comment]
Great!!! Thank you.

**Comment by brandonseydel** [comment]
This is in the latest code will be releasing nuget package tonight.
