### ISSUE TITLE
Double opt-in Emails?

### ISSUE THREAD

**Issue by seraphx2** [brandonseydel/MailChimp.Net#274]
I don't have the paid version so can't get direct help from mailchimp so maybe you guys will know how to handle this. My list is not set to double opt-in, but it seems that some people are getting an email in Bulgarian that wants them to confirm their email or something. Am I missing a setting in Mailchimp or in my API calls that would stop that? Does anyone know why they are getting them in Bulgarian?

**Comment by seraphx2** [comment]
I have figure everything out what my problem was. Sorry for this.

**Comment by DecimalTurn** [comment]
For anyone that finds this later, I'm assuming you went to Settings > Audience name and campaign defaults
Ans then unchecked "Enable double opt-in"
![image](https://github.com/brandonseydel/MailChimp.Net/assets/31558169/0bb42ed4-1a6c-4bfd-a690-5502429263c8)

Also note that accoding to this [SO answer](https://stackoverflow.com/a/31251526/5958842) you can make a specific member go through the whole double opt-in process without changing that setting at the list (audience) level. You simply need tot set the new member's status to "Pending" instead of "Subscribed" when you add it to the list.
