### ISSUE TITLE
Acessing MailChimpException.Data throws System.ArgumentException after upgrade to 3.4.1 version

### ISSUE THREAD

**Issue by boudinov** [brandonseydel/MailChimp.Net#419]
Upgraded MailChimp.Net from 3.2.1 to 3.4.1.
It destroyed our production environment, as our Azure Table logging crashes the whole process, because exception serialization fails inside .net framework code, because of the Data property throwing this exception.

I have seen this in two scenarios calling Members.AddOrUpdateAsync (i guess all mailchimp exception currently have this problem):
1.  Exception when i cannot change email of unsubscribed member
2.  Exception when i cannot add a new member, which was already permanently deleted

**Comment by brandonseydel** [comment]
The latest version is 4.2.0.  Can you bump your nuget to that as it works correctly?  I replicated what you are saying on latest and it correctly caught the error.

**Comment by boudinov** [comment]
Sorry, i actually updated version from 2.1 to 4.1.
Now, after updated to 4.2, the issue is still there.
![image](https://user-images.githubusercontent.com/7290779/62706458-40b2d300-b9f8-11e9-969c-d9b8ff0d924c.png)

**Comment by Eibx** [comment]
We're also experiencing this. 

I made a [PR a while ago](https://github.com/brandonseydel/MailChimp.Net/pull/362) to fix a similar issue regarding accessing `Data` twice, giving the same error.

I would assume this issue occurs because the `base.Data` inside [MailChimpException.cs](https://github.com/brandonseydel/MailChimp.Net/blob/master/MailChimp.Net/Core/MailChimpException.cs#L86) already contains one of the properties `detail`, `title`, `type`, `status`, `instance`, `errors` or `rawhttpresponsemessage` - and adding the same key twice to a dictionary throws an `System.ArgumentException`.

I think there are 3 ways to solve it.

1. Is to overwrite the property using `data["detail"] = Detail` instead of `data.Add` - this will of course overwrite potentional important information.

2. Is to change the property keys either by giving them different names or by prefixing them with something. This might be a breaking change, and will only make the issue less likely.

3. Make some logic that suffixes an incremental number as long as the key is present in the dictionary. This makes the method more complicated and might be overkill, but it retains the original names unless an duplicate is found and no data is lost.

**Comment by Eibx** [comment]
@brandonseydel If you have any preferences to my comment above or any suggestion of your own, I'll be more than happy to make a pull request.

**Comment by rosrosros** [comment]
@brandonseydel It would be great if you would comment on @Eibx 's comment
