### ISSUE TITLE
Creating a campaign using an existing template

### ISSUE THREAD

**Issue by strigi** [brandonseydel/MailChimp.Net#75]
Hi, 

I'm trying to figure out how to attach an existing template (by template_Id) to a new campaign and send it. I've tried Campaign.Setting.TemplateId with no luck. 

I also tried setting campaign's content using Template.Id, after the campaign is created. Still, no luck.

This one doesn't work either:

var contentRequest = manager.Templates.GetAsync(_Template_Id);
Template _fetchedTemplate = contentRequest.Result;

var _result2 = manager.Content.AddOrUpdateAsync(_Campaign_Id, new MailChimp.Net.Core.ContentRequest { Template = _fetchedTemplate } );

Thanks!

**Comment by brandonseydel** [comment]
```CSharp
new ContentRequest{Template = new Template{
Id = yourTemplateId
}}
```

**Comment by dougvdotcom** [comment]
On this subject: It would be helpful to implement template sections (that is, a Dictionary<string, string> for mc:edit fields in a template).

I can certainly see the value of sending static content via a template, but in many cases I need to customize some small part of the template to the user, e.g., add her name to the message; indicate a dynamically calculated date ("This offer expires on <mc:edit id="expireDate">", where expireDate = DateTime.UtcNow.AddDays(7)).

Thanks for a great library!

**Comment by dougvdotcom** [comment]
Confirming this issue. Code below does not seem to generate exceptions, but it also fails to set the designated template as the campaign content.

`var content = new ContentRequest
{
	Template = new Template
	{
		Id = 372497
	}
};

try
{
	await Manager.Content.AddOrUpdateAsync("89fe0e4766", content);
	return RedirectToAction("Detail");
}
catch (MailChimpException mce)
{
	return new HttpStatusCodeResult(HttpStatusCode.BadGateway, mce.Message);
}
catch (Exception ex)
{
	return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable, ex.Message);
}`

A wild guess is that the Template model is not the same for PUT /campaigns/{campaign_id}/content as it is for {VERB} /templates/?{templateid}. In the former case one sends only an ID and optional sections; in the latter, one sends the ID and the HTML of the template. 

It may be that because the objects are different, once sent to the MailChimp API, it is confused by the presence of illegitimate parameters and therefore fails silently.

Again, just a wild stab.

![screenshot-us9 admin mailchimp com 2016-08-13 20-12-20](https://cloud.githubusercontent.com/assets/667111/17646317/59f6d940-6192-11e6-9c37-2a40c0f0c2ad.png)

**Comment by strigi** [comment]
@Dougvdotcom thank you. Glad to know i was not imagining things. Either way i tried, i simply couldnt update a campign with a template.

**Comment by strigi** [comment]
@brandonseydel  Hi, 
Any update on that? I experience the same results as @dougvdotcom

**Comment by brandonseydel** [comment]
I bet it is sending default values for some of those booleans.  I am creating ContentTemplate class stripped down and adding in missing query string parameters

**Comment by strigi** [comment]
@brandonseydel was it helpful? :)
When do you think a new release is set?

**Comment by NoelOConnell** [comment]
I can confirm the same issue.

Adding [JsonProperty("template")] to Template in the ContentRequest resolved the issue.
Hope that helps.

**Comment by dougvdotcom** [comment]
Thanks @NoelOConnell and @brandonseydel 

Pull request issued with noted fix.
